site_name: Amino.fix.fix
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        options:
          docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition